# Generated by Django 4.1 on 2023-02-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Organization Name')),
                ('logo', models.CharField(default='logo', max_length=300, verbose_name='logo')),
                ('website', models.URLField(max_length=300, verbose_name='website link')),
                ('bio', models.TextField()),
                ('headquater', models.CharField(max_length=200, verbose_name='Headquater')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Organization logo')),
            ],
        ),
    ]
